spring:
  application:
    name: cloud-alibaba-dubbo-provider-hmy
  cloud:
    nacos:
      discovery:
        cluster-name: ${spring.application.name}
        server-addr:  112.74.42.138:8848

  # dubbo 相关配置
  datasource:
    # 初始化线程池数量  最大数  最小数
    type: com.alibaba.druid.pool.DruidDataSource
    # 驱动包 8.0以上的配置
    # =========== durid 连接池配置===========
    druid:
      #===========JDBC 配置===========
      url: jdbc:mysql://120.25.203.58:3317/db_movies?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
      username: root
      password: 123456
      initial-size: 5
      max-active: 20
      min-idle: 3
dubbo:
  scan:
    # 必须放在最前面
    # dubbo 服务扫描基准包
    base-packages: com.smart.dubbo.provider.service
  protocol:
    # dubbo 协议
    # http  协议
    # Hessian 协议
    # thrift 协议
    # RMI
    name: dubbo
    # dubbo 协议端口（ -1 表示自增端口，从 20880 开始）
    port: -1
  registry:
    address: nacos://112.74.42.138:8848
server:
  port: 9000